language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz

install:
 - "echo Python $TRAVIS_PYTHON_VERSION"
 - "pip install -r requirements/development.txt --use-mirrors"
 - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -wn pycallgraph; 2to3 -wn test; fi"

script: py.test
